### ISSUE TITLE
invalid character 'T' looking for beginning of object key string

### ISSUE THREAD

**Issue by guerillagorilla** [bemasher/rtlamr-collect#1]
Running rtlamr shows:
guerilla@guerilla:~/work/bin$ ./rtlamr
{Time:2017-12-21T22:58:44.319 SCM:{ID:34060345 Type: 4 Tamper:{Phy:00 Enc:00} Consumption:   12342 CRC:0x32D5}}
{Time:2017-12-21T22:58:44.873 SCM:{ID:42763095 Type: 5 Tamper:{Phy:03 Enc:00} Consumption: 3966871 CRC:0xF9D1}}

When running ./rtlamr | ./rtlamr-collect I get:
 23:01:11.658915 main.go:155: connecting to "user"@"http://localhost:8086"
23:01:11.660034 main.go:130: Preloaded: 0
23:01:11.773823 main.go:179: invalid character 'T' looking for beginning of object key string
23:01:12.831929 main.go:179: invalid character 'T' looking for beginning of object key string

Are there additional requirements that I'm missing in the installation or execution?  Seems like the regex used may be incorrect.

Appreciate any help.

**Comment by bemasher** [comment]
rtlamr-collect doesn't use regex for parsing it's input, the json decoder provided in the go standard library is used to parse messages.

Invocation without providing flags to rtlamr assumes that you have set the appropriate values through environment variables instead. If you want to configure rtlamr with command line flags, you must provide the following at a minimum:

    rtlamr -msgtype=idm -format=json -filterid=00000000 | rtlamr-collect

Replacing `00000000` with your meter's id. Also keep in mind that rtlamr-collect only supports IDM packets at the moment.

At the moment rtlamr-collect is only configurable with environment variables, so be sure to set the following variables appropriately before execution:

    COLLECT_INFLUXDB_HOSTNAME=localhost
    COLLECT_INFLUXDB_USER=username
    COLLECT_INFLUXDB_PASS=password

**Comment by guerillagorilla** [comment]
Got i!  Thanks very much for the assistance and the tool!
