### ISSUE TITLE
New version: rtl_tcp crashed

### ISSUE THREAD

**Issue by mash55** [bemasher/rtlamr-collect#13]
pls disregard for now... i had an epiphany

**Comment by bemasher** [comment]
Some of the environment variables have breaking changes between d0c151428bb2ee3875ca8b6a8f3c4f49dffcc49d and e5b1a1e9e581691e67d837e5f9bb57a5b743d820.

The documentation in README.md was updated to reflect the new behavior in e5b1a1e9e581691e67d837e5f9bb57a5b743d820.

I would also recommend updating rtlamr to the latest commit on the master branch.
