### ISSUE TITLE
Feature Request: r900, Leak information

### ISSUE THREAD

**Issue by mash55** [bemasher/rtlamr-collect#14]
Would it be possible to extract the LEAKINFORMATION from the r900 protocol as well?
Here what my water meter is broadcasting:
`{Time:2019-01-24T08:06:24.878 R900:{ID:1471517160 Unkn1:0xA1 NoUse: 0 BackFlow:0 Consumption: 2381589 Unkn3:0x00 Leak:15 LeakNow:3}}`
I assume it would be possible to set/create an alert in Grafana when a leak occurs... 
Thanks

**Comment by bemasher** [comment]
Which fields would you like to collect?

**Comment by mash55** [comment]
Don't know the difference between 'Leak' and 'LeakNow' - so why not collect both?

**Comment by jreiners** [comment]
I agree with that, I log complete weather data cloud wind 9mph, timed speed
tests, and all possible variables. It's an obsession.

**Comment by bemasher** [comment]
63080cff6176dd5be9f6b8e0373ff6589fedd4fb adds fields `NoUse`, `BackFlow`, `Leak`, and `LeakNow` for R900 and R900BCD.
