### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by mash55** [bemasher/rtlamr-collect#16]
Thanks bemasher, works like a charm. Decoding the r900 on a raspberry with 4 meters and 3 protocols seems to be too much. Missing many packets. Moving the r900 decoding to a separate pi seems to work... did no miss one beat from all 4 meters so far. Thanks for the quick implementation.

**Comment by bemasher** [comment]
No problem. The R900 decoder requires some extra matched filters to decide the symbols the protocol uses, so it is more intensive to decode and requires a bit more than an RPi can give without shortening the symbol length.
