### ISSUE TITLE
Database provisioning

### ISSUE THREAD

**Issue by hagensieker** [bemasher/rtlamr-collect#2]
I've installed rtlamr and found my meter (THANKS!) now trying to do the database thing.  Installed Influxdb on Ubuntu 16.04, started it with influxd from the CLI and now trying to do this

> Provisioning influxdb can be done using the included initial schema (assuming you have the influx cli client installed):
> 
> influx -host "host" -username 'user' -password 'pass' -path "init.iql"

Best I can tell nothing is happening and no database is being created.  I'm sure I'm missing something. Rtlamr-collect is installed.

**Comment by bemasher** [comment]
That command is missing the `-import` flag, I ran into that last night. I'll correct the documentation.
