### ISSUE TITLE
Anaconda is there a way to run on windows

### ISSUE THREAD

**Issue by computerfreek274** [bemasher/rtlamr-collect#20]
I would love to set this up on windows using anaconda is there a way ?

**Comment by bemasher** [comment]
I'm not sure what you mean by using anaconda, rtlamr and rtlamr-collect are both written in Go, you would need the go tool-chain to build and use it.

Please follow these instructions to install go on windows:
 * https://golang.org/dl/
 * https://golang.org/doc/install
