### ISSUE TITLE
Using 2 instances on rtlamr-collect

### ISSUE THREAD

**Issue by RamSet** [bemasher/rtlamr-collect#21]
Hello.

Wandering if there a parameter or support for defining the source of rtl_tcp for aggregation.

As in 2 dongles, on different Ips.

Aggregation/influxdb is on IP1, second dongle is on IP2 (doesn't have that much firepower to run rtlamr on it but it's ok with rtl_tcp serving).
Was wondering if i can run a different instance of rtlamr-collect on IP1 with IP2 as it's data source

**Comment by bemasher** [comment]
rtlamr-collect does not connect to the spectrum server, it only interprets messages read from stdin.

You can set the spectrum server for each instance of rtlamr using the `-server` command line flag, or `RTLAMR_SERVER` environment variable.
