### ISSUE TITLE
404 Error 

### ISSUE THREAD

**Issue by gogamga** [bemasher/rtlamr-collect#27]
Getting a 404 error connecting to InfluxDB after triple checking credentials and host (same box). Does this require telegraf to work?

![image](https://user-images.githubusercontent.com/37684334/96618360-d8859f80-12d2-11eb-8670-da28ff3e157d.png)

**Comment by bemasher** [comment]
Can you tell me which version of influxdb you're running? Their API is changing and I've not yet moved to the v2 go client.

**Comment by zenbane** [comment]
I am on 1.6.4-1 - do I need Telegraf running as well to ingest?

**Comment by gogamga** [comment]
I am on 1.6.4

**Comment by bemasher** [comment]
Hmm, the API shouldn't be incompatibly different. Can you tell me what you specified for `COLLECT_INFLUXDB_HOSTNAME`?

**Comment by gogamga** [comment]
![image](https://user-images.githubusercontent.com/37684334/96881584-6c2eab80-144c-11eb-892e-d615e0b33437.png)

It's running on the same host.

**Comment by bemasher** [comment]
This issue is probably different now that the influxdb client has been upgraded. Let me know if you still have similar problems in the new one.
