### ISSUE TITLE
InfluxDB 2 support

### ISSUE THREAD

**Issue by ccutrer** [bemasher/rtlamr-collect#29]
title says it all. currently you're using the v1 influx db client, and the v2 one is available at https://github.com/influxdata/influxdb-client-go. It still supports InfluxDB 1.8, so there is an upgrade path for users

**Comment by bemasher** [comment]
A draft is in the works. I'm testing on my home setup and will hopefully have something released in a little while.

The meter preloading is also being tossed and will instead persist data to disk with boltdb.

**Comment by ccutrer** [comment]
awesome, thanks!

**Comment by konstk1** [comment]
+1
