### ISSUE TITLE
Not issue, but general question

### ISSUE THREAD

**Issue by jreiners** [bemasher/rtlamr-collect#3]
I was wondering what unit the readings are in within influxdb, I'm using grafana to graph and it's working nicely but my readings all seem really small (300-1500) for a dryer, heater in garage, lights, and vacuums running. The graph does seem to match my usage patterns to a tee, it's just the numbers seem off to me. I just wonder if I need to move the decimal point or something.

**Comment by bemasher** [comment]
I imagine this will depend on your meter, but as far as I am aware, most residential meters transmitting IDM's report at 10 Wh intervals, which rtlamr-collect accounts for. In grafana, setting the units to Wh is what you'll need to have accurate results. But also keep in mind that each data point reported is over a 5 minute interval.

Having compared my meter's output over time with my bill, it matches almost exactly.

**Comment by jreiners** [comment]
Thank you, that's exactly the info I was looking for, also thank you for your work on rtlamr and rtlamr-collect. It's working nicely on my Raspberry Pi, and I've ordered another sdr so I can grab scm for my other meters without skipping a beat. This project got me and at least 2 coworkers into the sdr hobby.

**Comment by bemasher** [comment]
Awesome. It's definitely a lot of fun to mess around with. That's all this project started as.
