### ISSUE TITLE
Print collected data to stdout

### ISSUE THREAD

**Issue by konstk1** [bemasher/rtlamr-collect#31]
Previous version of rtlamr-collect would print the collected data to stdout and I noticed that current version does not. Is there a flag to turn that on?

Thanks for a great tool!

**Comment by dholt** [comment]
You can just use the `tee` command, i.e. `rtlamr ... | tee rtlamr-collect`

**Comment by konstk1** [comment]
> You can just use the `tee` command, i.e. `rtlamr ... | tee rtlamr-collect`

That does not work. In fact, the above will just overwrite your executable with output of `rtlamr` as it's treating `rtlamr-collect` as output file name, if you're providing full path.

There is a way to tee into another command but it's not immediately clear for me how to set that up. `rtlamr ... | tee >(rtlamr-collect)` doesn't seem to work either.

**Comment by dholt** [comment]
You're right, sorry, hasty suggestion. I'm not getting any data into the database so was trying to troubleshoot

**Comment by dholt** [comment]
Looks like you can do something like this: `rtlamr ... | tee /dev/tty | rtlamr-collect`

**Comment by bemasher** [comment]
@kostyan5 you can now use `COLLECT_LOGLEVEL=trace` to tell rtlamr-collect to print received messages.
