### ISSUE TITLE
stumped on "COLLECT_INFLUXDB_TOKEN" undefined

### ISSUE THREAD

**Issue by martysm** [bemasher/rtlamr-collect#32]
hi.
I hate to bother you, but I've got rtl_tcp running as a service and I can connect to it manually with RTLAMR, see my meter, filter for its ID and message type, output as csv and open it in excel, etc. but I cannot, for the life of me, get RTLAMR-COLLECT.service to start.

The relevant journalctl entry(s) for the service are:
```
--------------------------------------------
Feb 17 07:16:41 cubox-i sh[15412]: FATA[2021-02-17 07:16:41.332]/root/go/src/github.com/bemasher/rtlamr-collect/main.go:339 main.lookupEnv "COLLECT_INFLUXDB_TOKEN" undefined
Feb 17 07:16:41 cubox-i systemd[1]: rtlamr-collect.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 07:16:41 cubox-i systemd[1]: rtlamr-collect.service: Failed with result 'exit-code'.
---------------------------------------------
```
I thought maybe it was the "&" in my influxdb PW but I changed that, and still got the error.
I thought maybe there was a path issue but I checked and /root/go/src/github.com/bemasher/rtlamr-collect is where it is supposed to be.

Have you seen this issue before?  Any clues as to where to start.  I'm kind of a noob wrt Influxdb but I followed a tutorial and was able to create a user and a database and the influxdb service is running fine as near as I can tell.  Any help you can offer would be greatly appreciated.  Thanks.

**Comment by martysm** [comment]
Hi again.  You can close this.  I figured it out.  I have influx 1.8.4 and I found your documentation on the additional variables that needed to be defined in the .env so I now have a green light on the service.  I think I have to go to influx school for a while.  
I presume this looks normal?:

```
root@cubox-i:/etc/systemd/system# systemctl status rtlamr-collect
● rtlamr-collect.service - RTLAMR Collector
     Loaded: loaded (/etc/systemd/system/rtlamr-collect.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-02-17 22:01:34 UTC; 2min 14s ago
   Main PID: 4960 (sh)
      Tasks: 22 (limit: 4155)
     Memory: 7.0M
     CGroup: /system.slice/rtlamr-collect.service
             ├─4960 /bin/sh -c /root/go/bin/rtlamr | /root/go/bin/rtlamr-collect
             ├─4961 /root/go/bin/rtlamr
             └─4962 /root/go/bin/rtlamr-collect

Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.929248 decode.go:46: SampleRate: 2359296
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.929353 decode.go:47: DataRate: 32768
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.929547 decode.go:48: ChipLength: 72
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.929651 decode.go:49: PreambleSymbols: 21
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.929755 decode.go:50: PreambleLength: 3024
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.930134 decode.go:51: PacketSymbols: 96
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.930210 decode.go:52: PacketLength: 13824
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.930273 decode.go:59: Protocols: scm
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.930332 decode.go:60: Preambles: 111110010101001100000
Feb 17 22:01:34 cubox-i sh[4961]: 22:01:34.930399 main.go:119: GainCount: 29
```

**Comment by bemasher** [comment]
Yep. That looks normal. If you want to see received messages for debugging, set `COLLECT_LOGLEVEL=trace`

**Comment by martysm** [comment]
Doug- thank you for what you have done with this.  It's great to have all this info and "utilities" in one place.

I haven't yet got the influxdb configured correctly, but I have a .csv file growing larger every day with electrical and water usage.  The itron broadcasts about every 4-8s!  It serves my immediate purpose of avoiding a surprise bill when something like the a/c fan gets left on in the winter.  I will also be able to ID a water issue, should something happen.  The gazillion line .csv is inconvenient enough to motivate me to figure out docker/influxdb etc. If I fail, I'll fall back on a RTC to take a few lines every 4 hours or so.(:-))

Thanks again!

⁣Get TypeApp for Android ​

**Comment by martysm** [comment]
I discovered the -unique switch.  I feel much better now.  Dawn appears over Marblehead, every day, on this one.
