### ISSUE TITLE
Diagnosing Influx issues

### ISSUE THREAD

**Issue by sa7mon** [bemasher/rtlamr-collect#33]
Hi there,

I'm trying to get the tool setup and running in my network. I've got all the settings set to what I believe they should be, and stdout gives good-looking messages:

```
TRAC[2021-09-08 15:11:38.585]/home/dan/go/pkg/mod/github.com/bemasher/rtlamr-collect@v1.0.3/main.go:418 main.main {"Time":"2021-09-08T15:11:38.584869957-05:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":[redacted],"Type":7,"TamperPhy":2,"TamperEnc":3,"Consumption":7361312,"ChecksumVal":20145}}
TRAC[2021-09-08 15:12:36.249]/home/dan/go/pkg/mod/github.com/bemasher/rtlamr-collect@v1.0.3/main.go:418 main.main {"Time":"2021-09-08T15:12:36.249756939-05:00","Offset":0,"Length":0,"Type":"SCM","Message":{"ID":[redacted],"Type":7,"TamperPhy":2,"TamperEnc":3,"Consumption":7361316,"ChecksumVal":29852}}
```

when I go to "Explore" the data in the InfluxDB web UI, I don't get any data points. I queried the bucket with the CLI tool and it also gives no data points.

Assuming there is an issue with my settings (which is likely), how can I go about seeing any errors the tool throws while trying to write data to the Influx API?

**Comment by bemasher** [comment]
`rtlamr-collect` should be loud about any errors encountered while writing data to InfluxDB. You may want to look at logs for `influxd`.

**Comment by sa7mon** [comment]
I did not get any errors from `rtlamr-collect` was very frustrated so I just wrote my own simple Python script to read in the output of `rtlamr` and POST the influx line protocol to my server.
