### ISSUE TITLE
Invalid character error

### ISSUE THREAD

**Issue by smrtsmrf** [bemasher/rtlamr-collect#34]
I downloaded v1.0.3 of this, along with v0.9.3 of `rtlamr`. I setup my influxdb configuration and when I run `rtlamr | rtlamr-collect`, I get this error whenever a consumption message comes in:

```
INFO[2021-09-13 21:12:45.864]/Users/candicehumpherys/go/src/github.com/bemasher/rtlamr-collect/main.go:424 main.main invalid character 'T' looking for beginning of object key string 
```

Running `rtlamr` by itself gives this output for a consumption message:
```
{Time:2021-09-13T21:15:10.112 SCM+:{ProtocolID:0x1E EndpointType:0x07 EndpointID:1552230918 Consumption:    387439 Tamper:0x0001 PacketCRC:0x0471}}
```

Note: A few months back I had v1.0.2 and v0.9.2, and everything was working fine.

**Comment by smrtsmrf** [comment]
@bemasher what am I missing?

**Comment by bemasher** [comment]
Rtlamr-collect requires JSON input, the default rtlamr output _looks_ like JSON but isn't actually JSON. You'll want to use the environment variable `RTLAMR_FORMAT=json` or the flag `-format=json`.

**Comment by smrtsmrf** [comment]
Doh. 🤦🏽‍♀️ I missed that one. Thank you. I will confirm when I get home tonight, but I'm pretty sure that's the solution.

**Comment by bemasher** [comment]
Closing, stale.
