### ISSUE TITLE
Can you give us some info on how to set up influxdb?

### ISSUE THREAD

**Issue by jas0995** [bemasher/rtlamr-collect#35]
I have never used influx and have not found the correct combination of parameters to get it to work.

After much messing around, I got rtlamr-collect to run without spitting out errors, but I don't see any info being inserted into influx.

I am running on linux with influx 2.x.
If I use the "tee" command I can see the json that is being sent to rtlamr-collect and it looks ok, but I don't have any way to diagnose what is going on with the connection to influx.

I tried several setting most of the env params to 'utilities' becase that is what I am monitoring, but in influx I see a bunch of other data in there.  It looks like that is used by influx as an example or something.

I changed everything to rtlamr, but I have an empty bucket with no info.  I generate and set the access token each time.

Thanks
-John

**Comment by bemasher** [comment]
John, your question is kind of out of scope for this project. It sounds like you are using InfluxDB v2, the exploration tab of the baked-in web interface is a good place to start to figure out where the data is ending up.
