### ISSUE TITLE
Where to set envinronment variables (Using Windows)

### ISSUE THREAD

**Issue by ricardolca** [bemasher/rtlamr-collect#36]
Hello, thank you for the great work you have done with both rtlamr and rtlamr-collect.

I was reading the documentation, and it is clear that we should use the enironment files to configure some parameters, like the host for the influx DB.

However, I am running rtlamr and rtlamt-collect on windows and I am unsure where should I place these files *.env.

Could you kindly assist on this info?

Thank you

**Comment by ricardolca** [comment]
Thank you, I just figured it out...You can type direct on the command prompt or using a bat file.

Example, type on command prompt set RTLAMR_FILTERID=00000000, where 00000000 is your meter number.

Thanks!

**Comment by cypherstream** [comment]
Thanks, here I was trying to put them in user variables and when that didnt work system variables and neither worked...  This was in sysdm.cpl (System Properties > Advanced > Environment Variables button.
