### ISSUE TITLE
COLLECT_INFLUXDB_HOSTNAME undefined

### ISSUE THREAD

**Issue by deroses** [bemasher/rtlamr-collect#4]
I've followed `rtlamr` instructions and can happily stream that data.  

I've verified that the `rtlamr-collect` prerequisites are installed and working, but I've got some error with my env file.  Whether I attempt to pipe `rtlamr` output to `rtlamr-collect`, or just attempt to run `rtlamr-collect` directly: I get `COLLECT_INFLUXDB_HOSTNAME undefined` as a response.  

I'm not sure how to get it to correctly read `rtlamr-collect.env`.  I am on a macbook pro (sierra).  

Apologies for the setup question - thank you for the work on this project.  Happy to help better define or diagnose the issue that I am having.

**Comment by jreiners** [comment]
You just need to add the 2 environmental variables from the .env to your
Mac I'm pretty sure. Rtlamr collect needs them for influxdb.

Bemasher has a good write-up in his readme as well, and I also got stuck on
that part.

**Comment by bemasher** [comment]
Keep in mind that `rtlamr-collect.env` is only used when running rtlamr-collect as a systemd unit where it is loaded and provides it's contents as environment variables to the process.

If you are not running rtlamr-collect as a systemd unit, you will need to set those environment variables before running the application, I would recommend exporting the variables in a script that also launches rtlamr-collect.

**Comment by deroses** [comment]
Thanks to you both - that fixed my problem!
