### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by taciturnaxolotl** [bemasher/rtlamr-collect#44]
Could you share the dashboard you made? It looks very good! I've been having trouble getting Grafana to sort the input data by ID, so I can graph it as a bar graph. Any help would be appreciated. Thanks for creating this project!

**Comment by zachliu** [comment]
depending on your needs & the resources you have, for example
* i don't want to run a full-blown home server 24/7
* i need dashboard access when i'm not at home
* i don't want to build infrastructures from scratch on aws

 so i chose the combination of raspberry pi + aws quicksight
* raspberry pi runs 24/7 collecting, parsing, uploading data to s3
* quicksight provides the dashboards st i can access it on my phone
