### ISSUE TITLE
add msgtype: r900

### ISSUE THREAD

**Issue by egardiner** [bemasher/rtlamr-collect#6]
rltamr-collect looks awesome - thanks!  Will you consider adding support for water consumption (i.e. Neptune r900 meters)?  I'd love to use this to visualize water usage.

**Comment by bemasher** [comment]
At the moment I don't have any concrete plans for adding support to meters that do not provide consumption history like SCM, SCM+, and R900. It may happen in the future though.

The main difficulty is avoiding recording duplicate messages and handling transmit offset times, none of which are provided in those messages types.
