### ISSUE TITLE
Where to put environment variables?

### ISSUE THREAD

**Issue by poorredneck** [bemasher/rtlamr-collect#7]
I know this isn't a specific issue but I'm out of ideas. I have edited ~/.profile and added the variables, rebooted but I still get the error:  

```
someuser@orangepi:~$ rtlamr -format=json -msgtype=idm | rtlamr-collect
15:47:47.545679 decode.go:43: CenterFreq: 912600155
15:47:47.548426 decode.go:44: SampleRate: 2359296
15:47:47.550024 decode.go:45: DataRate: 32768
15:47:47.550459 decode.go:46: ChipLength: 72
15:47:47.550730 decode.go:47: PreambleSymbols: 32
15:47:47.551254 decode.go:48: PreambleLength: 4608
15:47:47.551542 decode.go:49: PacketSymbols: 736
15:47:47.551945 decode.go:50: PacketLength: 105984
15:47:47.552197 decode.go:51: Preamble: 01010101010101010001011010100011
15:47:47.552446 main.go:94: GainCount: 29
15:47:47.560325 main.go:139: COLLECT_INFLUXDB_HOSTNAME undefined
```

My ~/.profile contains this:

```
COLLECT_INFLUXDB_HOSTNAME="localhost";
COLLECT_INFLUXDB_USER="someuser";
COLLECT_INFLUXDB_PASS="somepass";
COLLECT_MULTIPLIER="10";
RTLAMR_MSGTYPE="idm";
RTLAMR_FORMAT="json";
```

I execute from the terminal this command:

`rtlamr -format=json -msgtype=idm | rtlamr-collect`

I should add that all parts of rtlamr is working fine, I can | output to a log file, have a crontab running and manually processing/parsing the .csv files just to "get it running" and have proof that I can get this far. 

Ultimately the beautiful grafana and Cronografs are what I'm after. I'm starting with Cronograf & InfluxDB. I have Cronograf and InfluxDB all working, the rtlamr database was created as outlined in the readme. I'm just having a stupid issue with the environment variables (I am still a linux newbie). I can curl the influxdb and get responses so the database is working/reachable.

Any assistance is greatly appreciated, and many many thanks for these excellent utilities!

**Comment by bemasher** [comment]
Environment variables in `~/.profile` will need to be exported:

```bash
export COLLECT_INFLUXDB_HOSTNAME="localhost"
export COLLECT_INFLUXDB_USER="someuser"
export COLLECT_INFLUXDB_PASS="somepass"
export COLLECT_MULTIPLIER="10"
export RTLAMR_MSGTYPE="idm"
export RTLAMR_FORMAT="json"
```

You also don't need semi-colon's at the end of each line.

**Comment by poorredneck** [comment]
Thank you so much! I now have Grafana 5.x working on my Orange Pi, have a few test tables setup (only about 2 hours of data so far so not much experimenting) but do have the every data!

I have a question about the COLLECT_MULTIPLIER

When I view the RTLAMR data raw, just in format=plain my meter reads dWh I think.... Basically the consumption looks like this: 6122859. I have to divide by 100 to get the KWh (which is what I'm more familiar with, and billed by). So the actual KWh displayed on the meter is 61228.59. Should I leave COLLECT_MULTIPLIER=10?

I guess I can change the data in grafana but I'm not sure if the data I'm looking at is actually being represented in Watt Hours or not. I've attached a screenshot.

![5 minute2](https://user-images.githubusercontent.com/15825016/37871632-948af8c2-2fc0-11e8-866a-4c466aef06db.jpg)
![5 minute](https://user-images.githubusercontent.com/15825016/37871633-94a21796-2fc0-11e8-8053-a073bb779959.JPG)

**Comment by poorredneck** [comment]
Awesome thank you!!!!
