### ISSUE TITLE
COLLECT_MULTIPLIER - Interpreting Consumption Values in KWh or Wh

### ISSUE THREAD

**Issue by poorredneck** [bemasher/rtlamr-collect#8]
I have a question about the COLLECT_MULTIPLIER

When I view the RTLAMR data raw, just in format=plain my meter reads dWh I think.... Basically the consumption looks like this: 6122859. I have to divide by 100 to get the KWh (which is what I'm more familiar with, and billed by). So the actual KWh displayed on the meter is 61228.59. Should I leave COLLECT_MULTIPLIER=10?

I guess I can change the data in grafana but I'm not sure if the data I'm looking at is actually being represented in Watt Hours or not. I've attached a screenshot.

![5 minute](https://user-images.githubusercontent.com/15825016/37871633-94a21796-2fc0-11e8-8053-a073bb779959.JPG)

![5 minute2](https://user-images.githubusercontent.com/15825016/37871668-6494f928-2fc1-11e8-9aa4-76ee3e5d82c7.jpg)

**Comment by bemasher** [comment]
The goal of the multiplier is usually to get to a known unit like Wh or kWh. For most power meters, you'll want a multiplier of 10 to get to Wh, then you can set the units the same in Grafana or Chronograf and they will adjust magnitude of units shown based on actual consumption.

**Comment by poorredneck** [comment]
Ok. I'm assuming everything is reading correctly then. I'll need to let it collect enough data to compare it to a bill I suppose. I expected with my dryer running, that it'd be showing more consumption. Electric dyer is about 3,800W (measured with amp-probe 16A @ 240V US). SO I would assume my usage at that time would be atleast 3.8KWH.... unless I'm thinking about Wh over time incorrectly (very likely). Example... If the dryer is 3800W, would the 5m consumption show 3,800Wh over a period of an hour? Or would it be 380Wh over an hour?

On an unrelated note, would you mind sharing your configuration settings for 3 graphs for 5m, 1h, 1d for grafana? This is my 5 min consumption graph. I just want to make sure I'm configuring it right.

![capture](https://user-images.githubusercontent.com/15825016/37878386-a26608e4-3036-11e8-9a89-42ffebf6c24e.JPG)

**Comment by poorredneck** [comment]
Also, does RTLAMR-COLLECT store the actual "consumption" value in InfluxDB some where (the number that matches what is on the meter) so I can display a "current meter reading" like I am the "current consumption" in the image below? 

![capture2](https://user-images.githubusercontent.com/15825016/37878410-fc247046-3036-11e8-8f5f-9a4472894de0.jpg)

**Comment by poorredneck** [comment]
And again, I can not thank you enough for all your work in these utilities. This was still a bit of a difficult project to get up and going to the point I am, but the fact that I got it working is a testament to your hard work on these utilities. I've seen write ups done years ago before this utility existed and there's NO WAY I could have gotten that to work. 

I've wanted the "Sense" monitoring device for a while, but can't justify the cost yet. I'm hoping this is going to do 80% of what Sense does.... which for me is focusing on how my HVAC settings affect my consumption on a daily basis to keep variables down and make changes quickly.

So yeah.... THANKS AGAIN bemasher!!!

**Comment by bemasher** [comment]
You should be able to import the attached file into grafana for a new dashboard.

[Energy-1522009999967.txt](https://github.com/bemasher/rtlamr-collect/files/1845767/Energy-1522009999967.txt)

The actual consumption value isn't stored anywhere in influxdb since it is mostly meaningless without other data to relate it to. You could modify rtlamr-collect to include it.

  * It would need to be added to this type: https://github.com/bemasher/rtlamr-collect/blob/master/main.go#L46
  * And added to this type: https://github.com/bemasher/rtlamr-collect/blob/master/main.go#L68
  * And added as a new key to this map: https://github.com/bemasher/rtlamr-collect/blob/master/main.go#L75
  * And stored in the Consumption type from the IDM type here: https://github.com/bemasher/rtlamr-collect/blob/master/main.go#L80
