### ISSUE TITLE
Autostart Issues

### ISSUE THREAD

**Issue by poorredneck** [bemasher/rtlamr-collect#9]
bemasher I can't thank you enough for your help, and I hope this is the last problem I have.

I have tried to auto-run the "command" with a crontab, rc.local, and systemd service. 

I have a file "log_energy.sh" that is chmod +x executable. It is simply this:
```
#!/bin/bash
/home/jonboy545/GoCode/bin/rtlamr -filterid=62059972 -format=json -msgtype=idm unique=true | /home/jonboy545/GoCode/bin/rtlamr-collect;
```

If I'm in a terminal window at ~, and type ./log_energy.sh & disown it works perfectly. Also, if I open a SCREEN instance, execute ./log_energy.sh and then detach from that screen instance it works fine.

So I tried putting that script file into rc.local. I had to put a sleep 120 in there to get it to execute otherwise I think it started too soon. However after a few minutes it rtlamr abruptly stops for some reason. I do not have this issue if I start the log_energy.sh file from a terminal. It will run indefinitely.

This is what my rc.local looks like:
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

/bin/sh /root/vnc.sh &

rtl_tcp &

sleep 120

/home/jonboy545/log_energy.sh &


exit 0
```

So since I'm on an OrangePi running Ubunto 16.04 I tried making a systemd service.

energy.service looks like this: (I followed the guide here: https://askubuntu.com/questions/913838/writing-systemd-script
```
[Unit]
Description=Energy Monitor Script

[Service]
ExecStart=/home/jonboy545/GoCode/bin/rtlamr -filterid=62059972 -format=json -msgtype=idm unique=true | /home/jonboy545/GoCode/bin/rtlamr-collect

[Install]
WantedBy=multi-user.target
```
Then chmod 644 energy.service

Then per the instruction: `sudo systemctl enable energy.service`

For the life of me, I can not get this thing to auto-run at boot reliably! 

I'm so sorry for asking all these questions, not related specifically to rtlamr but you have been so responsive I can't help it :-(

Thank you so much in advance,
Jonathan

**Comment by bemasher** [comment]
Have you tried using the provided systemd services?

**Comment by poorredneck** [comment]
Yes, but kept having issues with rtl_tcp not wanting to start. rtl_ctp was in /usr/local/bin not /usr/bin so fixed that now service is working great!

I have an un-related question, didn't want to open an "issue" on it...

How does rtlamr-collect handle "down time"? Since the total consumption is monitored over time, it never really "loses track" of how much has been consumed.

So for example: my OrangePi locked up ths morning (still trying to figure out why this is happening every couple days). So it was an hour or so before I got home and was able to power cycle the machine.

Once everything re-started, the "dead space" in grafana is all of a sudden filled in, but not with a flat line like I would have expected. Since there wasn't any data written to the database in over an hour, I figured next time it gets a consumption reading, it'll be like an "average" but there are "valid" (are they valid?) data points written to the database in the dead time.

See the screenshot. The box highlighted red is when the system was down, so no data was being recorded to the influxdb but once rtlamr-collect was restarted the data points pop up. Again, I was expecting a "flat line" between dead time and current, since it doesn't know what the consumption was during that down time. 

How is the down time handled?


![capture](https://user-images.githubusercontent.com/15825016/38042927-ab49a688-3283-11e8-845d-c0fcf29fec76.JPG)

**Comment by bemasher** [comment]
Interval Data Messages contain differential consumption information. Each packet contains 47x5 minute intervals, each of which are the difference in consumption from one interval to the next, so rtlamr-collect can back-fill 3 hours 55 minutes worth of power usage if there is an interruption in messages.

This is nice because you don't need to hear every message in order to maintain full consumption history. rtlamr-collect will also pay attention to data it has already written to the database, so when it starts, it preloads the last 3h55m worth of data from influxdb to avoid writing duplicate points.
